/**
 * 
 * Copyright(c) ULTA, Inc. All Rights reserved. 
 *
 *
 */
package com.ulta.core.conf.types;



/**
 * The Enum CheckoutScreens.
 */
public enum CheckoutScreens {
	ADDNEWBILLINGADDRESSACTIVITY,
	ADDNEWCREDITCARDACTIVITY,
	ADDNEWSHIPPINGADDRESSACTIVITY,
	BILLINGADDRESSACTIVITY,
	EDITGIFTCARDACTIVITY,
	GIFTOPTIONACTIVITY,
	PAYMENTMETHODACTIVITY,
	PROMOCODEACTIVITY,
	REVIEWORDERACTIVITY,
	SHIPPINGADRESSACTIVITY,
	SHIPPINGMETHODACTIVITY	
}
