package com.ulta.core.conf.types;

public enum UserSpecificRetrieveDataScreen {
	LISTOFBILLINGADDRESSESACTVITY,
	LISTOFCREDITCARDDETAILSACTIVITY,
	LISTOFSHIPPINGADDRESSESACTVITY,
	MYACCOUNTACTIVITY,
	MYORDERHISTORYACTIVITY,
	MYPREFFEREDBILLINGADDRESSACTVITY,
	MYPREFFEREDSHIPPINGADDRESSACTVITY,
	PAYMENTMETHODLISTACTVITY,
	FAVORITESACTIVITY,
	REWARDSACTIVITY
	
}
